<?php

/**
 * @file
 * Contains entity_usage.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function entity_usage_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the entity_usage module.
    case 'help.page.entity_usage':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Track usage of entities referenced by other entities') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_insert().
 */
function entity_usage_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
//  return \Drupal::service('entity_usage.entity_update_manager')->trackUpdate($entity, 'insert');
}

/**
 * Implements hook_entity_update().
 */
function entity_usage_entity_update(Drupal\Core\Entity\EntityInterface $entity) {
//  return \Drupal::service('entity_usage.entity_update_manager')->trackUpdate($entity, 'update');
}

/**
 * Implements hook_entity_presave().
 */
function entity_usage_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $operation = $entity->isNew() ? 'insert' : 'update';
  return \Drupal::service('entity_usage.entity_update_manager')->trackUpdate($entity, $operation);
}

/**
 * Implements hook_entity_predelete().
 */
function entity_usage_entity_predelete(Drupal\Core\Entity\EntityInterface $entity) {
  return \Drupal::service('entity_usage.entity_update_manager')->trackUpdate($entity, 'delete');
}
